# Generated by Django 3.1.7 on 2022-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spec',
            field=models.CharField(default='', max_length=20),
        ),
    ]
