# Generated by Django 3.1.7 on 2021-12-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='pregancy_status',
            new_name='pregnancy_status',
        ),
    ]
