# Generated by Django 3.1.7 on 2022-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20211228_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.CharField(default='', max_length=20)),
                ('diabetes', models.CharField(default='', max_length=20)),
                ('asthma', models.CharField(default='', max_length=20)),
                ('seizure', models.CharField(default='', max_length=20)),
                ('kidney', models.CharField(default='', max_length=20)),
                ('systemic', models.CharField(default='', max_length=20)),
                ('hiv', models.CharField(default='', max_length=20)),
                ('heart', models.CharField(default='', max_length=20)),
                ('cancer', models.CharField(default='', max_length=20)),
                ('brain', models.CharField(default='', max_length=20)),
                ('hypothyroidism', models.CharField(default='', max_length=20)),
                ('hyperthyroidism', models.CharField(default='', max_length=20)),
                ('clotting', models.CharField(default='', max_length=20)),
                ('preeclampsia_prior', models.CharField(default='', max_length=20)),
                ('preeclampsia_after', models.CharField(default='', max_length=20)),
                ('preterm_delivery_prior', models.CharField(default='', max_length=20)),
                ('Rupture', models.CharField(default='', max_length=20)),
                ('Cerclage', models.CharField(default='', max_length=20)),
                ('uterine', models.CharField(default='', max_length=20)),
                ('Stillbirth', models.CharField(default='', max_length=20)),
                ('Intrauterine', models.CharField(default='', max_length=20)),
                ('trimester', models.CharField(default='', max_length=20)),
                ('bmi', models.CharField(default='', max_length=20)),
                ('Oligohydramnios', models.CharField(default='', max_length=20)),
                ('Polyhydramnios', models.CharField(default='', max_length=20)),
                ('IUGR', models.CharField(default='', max_length=20)),
                ('Fetal', models.CharField(default='', max_length=20)),
                ('ivf', models.CharField(default='', max_length=20)),
                ('age_years', models.CharField(default='', max_length=20)),
                ('multiple_gestation', models.CharField(default='', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
    ]
