# Generated by Django 3.1.7 on 2022-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_pramdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pramdata',
            old_name='Cerclage',
            new_name='cerclage',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='Fetal',
            new_name='fetal',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='IUGR',
            new_name='iugr',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='Oligohydramnios',
            new_name='oligohydramnios',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='Polyhydramnios',
            new_name='polyhydramnios',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='Rupture',
            new_name='preterm_delivery',
        ),
        migrations.RenameField(
            model_name='pramdata',
            old_name='Stillbirth',
            new_name='rupture',
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_bmi',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_edd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_ovulation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pramdata',
            name='stillbirth',
            field=models.CharField(default='', max_length=20),
        ),
    ]
