# Generated by Django 3.1.7 on 2022-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20220110_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.CharField(default='', max_length=20),
        ),
    ]
